[package]
authors = ["nathanjent <nathanjent@gmail.com>"]
name = "common"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
comrak = "0.1.8"

[dependencies.http]
git = "https://github.com/carllerche/http"
