# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: _site
  COBALT_VERSION: 'v0.19.2'

jobs:
# Please do not rename this job. It is used by ionos deploy now.
  build-project:
    name: build nathanjent.com
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Download Cobalt Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cobalt-org/cobalt.rs
          tag: ${{ env.COBALT_VERSION }}
          file: cobalt-${{ env.COBALT_VERSION }}-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract Cobalt Binary
        run: tar -xzf cobalt-$COBALT_VERSION-x86_64-unknown-linux-gnu.tar.gz ./cobalt

      - name: Build
        run: ./cobalt build

      - name: Clean
        run: rm -f ./cobalt ./cobalt-*.tar.gz

# Please do not touch the following action. It is used by ionos deploy now.
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 69de5756-d730-4a1a-9581-596c00d6a649
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/nathanjent.com/config.yaml
          action: upload
